CONFIG = { 
  :dc2019 =>       {:memory => 3072, :cpus => 2, :name => "dc2019",},
  :srv2019 =>      {:memory => 2048, :cpus => 2, :name => "srv2019"},
  :client =>   {:memory => 2048, :cpus => 1, :name => "client"}
}

Vagrant.configure("2") do |config|

  unless Vagrant.has_plugin?("vagrant-reload")
    raise 'vagrant-reload plugin is not installed!'
  end

  config.vm.define "dc2019" do |cfg|
    cfg.vm.box = "peru/windows-server-2019-standard-x64-eval"
    cfg.vm.hostname = CONFIG[:dc2019][:name]
    cfg.vm.boot_timeout = 600
    cfg.winrm.transport = :plaintext
    cfg.vm.communicator = "winrm"
    cfg.winrm.basic_auth_only = true

    cfg.winrm.timeout = 300
    cfg.winrm.retry_limit = 20
    cfg.vm.network :private_network, ip: "192.168.38.102", gateway: "192.168.38.1", dns: "8.8.8.8"

    # Added DNS here because libvirt fails to properly configure the windows client otherwise... :(
    cfg.vm.provision "shell", path: "resources/scripts/fix-second-network.ps1", preserve_order: true, privileged: true, args: "-ip 192.168.38.102 -dns 8.8.8.8 -gateway 192.168.38.1" 

    cfg.vm.provision "shell", path: "resources/scripts/provision.ps1", preserve_order: true, privileged: false
    cfg.vm.provision "reload"
    cfg.vm.provision "shell", path: "resources/scripts/provision.ps1", preserve_order: true, privileged: false
    cfg.vm.provision "shell", path: "resources/scripts/configure-ou.ps1", preserve_order: true, privileged: false
    cfg.vm.provision "shell", path: "resources/scripts/configure-rdp-user-gpo.ps1", privileged: false

    cfg.vm.provider "libvirt" do |libvirt, override|
      libvirt.cpus = CONFIG[:dc2019][:cpus] 
      libvirt.memory = CONFIG[:dc2019][:memory]
      # Relax constraints on timers
      libvirt.hyperv_feature :name => 'relaxed', :state => 'on'
      # Enable virtual APIC
      libvirt.hyperv_feature :name => 'vapic', :state => 'on'

      # sync_folder is not by default on all providers
      # Furthermore, it could not be the default provider :
      # https://github.com/Cimpress-MCP/vagrant-winrm-syncedfolders/issues/11

      # We'll need vagrant-winrm-syncedfolders plugin

      override.vm.synced_folder 'resources/', '/vagrant', type: 'winrm' 
    end

    cfg.vm.provider "vmware_desktop" do |v, override|
      override.vm.box = "detectionlab/win2019"
      v.vmx["displayname"] = CONFIG[:dc2019][:name] 
      v.memory = CONFIG[:dc2019][:memory] 
      v.cpus = CONFIG[:dc2019][:cpus] 
      v.gui = true
      v.enable_vmrun_ip_lookup = false
    end

    cfg.vm.provider "virtualbox" do |vb, override|
      vb.gui = true
      vb.name = CONFIG[:dc2019][:name] 
      vb.default_nic_type = "82545EM"
      vb.customize ["modifyvm", :id, "--memory", CONFIG[:dc2019][:memory] ]
      vb.customize ["modifyvm", :id, "--cpus", CONFIG[:dc2019][:cpus] ]
      vb.customize ["modifyvm", :id, "--vram", "32"]
      vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["setextradata", "global", "GUI/SuppressMessages", "all" ]

      override.vm.synced_folder './', '/vagrant', type: 'virtualbox'
    end

  end

  config.vm.define "srv2019" do |cfg|
    cfg.vm.box = "peru/windows-server-2019-standard-x64-eval"
    cfg.vm.hostname = CONFIG[:srv2019][:name]
    cfg.vm.boot_timeout = 600
    cfg.vm.communicator = "winrm"
    cfg.winrm.basic_auth_only = true
    cfg.winrm.timeout = 300
    cfg.winrm.retry_limit = 20
    cfg.vm.network :private_network, ip: "192.168.38.103", gateway: "192.168.38.1", dns: "192.168.38.102"

    cfg.vm.provision "shell", path: "resources/scripts/fix-second-network.ps1", preserve_order: true, privileged: true, args: "-ip 192.168.38.103 -dns 8.8.8.8 -gateway 192.168.38.1" 

    cfg.vm.provision "shell", path: "resources/scripts/provision.ps1",  preserve_order: true, privileged: false
    cfg.vm.provision "shell", inline: "cscript c:\\windows\\system32\\slmgr.vbs -rearm",  preserve_order: true, privileged: false
    cfg.vm.provision "reload"
    cfg.vm.provision "shell", path: "resources/scripts/provision.ps1",  preserve_order: true, privileged: false

    cfg.vm.provider "libvirt" do |libvirt, override|
      libvirt.cpus = CONFIG[:srv2019][:cpus] 
      libvirt.memory = CONFIG[:srv2019][:memory]
      # Relax constraints on timers
      libvirt.hyperv_feature :name => 'relaxed', :state => 'on'
      # Enable virtual APIC
      libvirt.hyperv_feature :name => 'vapic', :state => 'on'

      # sync_folder is not by default on all providers
      # Furthermore, WinRM could not be the default provider :
      # https://github.com/Cimpress-MCP/vagrant-winrm-syncedfolders/issues/11

      # We'll need vagrant-winrm-syncedfolders plugin

      override.vm.synced_folder 'resources/', '/vagrant', type: 'winrm' 
    end

    cfg.vm.provider "vmware_desktop" do |v, override|
      override.vm.box = "detectionlab/win2019"
      v.vmx["displayname"] = CONFIG[:srv2019][:name]
      v.memory = CONFIG[:srv2019][:memory]
      v.cpus = CONFIG[:srv2019][:cpus]
      v.gui = true
      v.enable_vmrun_ip_lookup = false
    end

    cfg.vm.provider "virtualbox" do |vb, override|
      vb.gui = true
      vb.name = CONFIG[:srv2019][:name]
      vb.default_nic_type = "82545EM"
      vb.customize ["modifyvm", :id, "--memory", CONFIG[:srv2019][:memory]]
      vb.customize ["modifyvm", :id, "--cpus", CONFIG[:srv2019][:cpus]]
      vb.customize ["modifyvm", :id, "--vram", "32"]
      vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["setextradata", "global", "GUI/SuppressMessages", "all" ]

      override.vm.synced_folder './', '/vagrant', type: 'virtualbox'
    end

  end

  config.vm.define "client" do |cfg|
    cfg.vm.box = "peru/windows-10-enterprise-x64-eval"
    cfg.vm.hostname = CONFIG[:client][:name]
    cfg.vm.boot_timeout = 1200
    cfg.vm.communicator = "winrm"
    cfg.winrm.basic_auth_only = true
    cfg.winrm.timeout = 1200
    cfg.winrm.retry_limit = 20
    cfg.vm.network :private_network, ip: "192.168.38.104", gateway: "192.168.38.1", dns: "192.168.38.102"
    
    cfg.vm.provision "shell", path: "resources/scripts/fix-second-network.ps1", preserve_order: true, privileged: true, args: "-ip 192.168.38.104 -dns 8.8.8.8 -gateway 192.168.38.1" 
    cfg.vm.provision "shell", path: "resources/scripts/MakeWindows10GreatAgain.ps1",  preserve_order: true, privileged: false
    cfg.vm.provision "shell", path: "resources/scripts/provision.ps1",  preserve_order: true, privileged: false
    cfg.vm.provision "shell", inline: "cscript c:\\windows\\system32\\slmgr.vbs -rearm",  preserve_order: true, privileged: false
    cfg.vm.provision "reload"
    cfg.vm.provision "shell", path: "resources/scripts/provision.ps1",  preserve_order: true, privileged: false

    cfg.vm.provider "libvirt" do |libvirt, override|
      libvirt.cpus = CONFIG[:client][:cpus] 
      libvirt.memory = CONFIG[:client][:memory]
      # Relax constraints on timers
      libvirt.hyperv_feature :name => 'relaxed', :state => 'on'
      # Enable virtual APIC
      libvirt.hyperv_feature :name => 'vapic', :state => 'on'

      # sync_folder is not by default on all providers
      # Furthermore, it could not be the default provider :
      # https://github.com/Cimpress-MCP/vagrant-winrm-syncedfolders/issues/11

      # We'll need vagrant-winrm-syncedfolders plugin

      override.vm.synced_folder 'resources/', '/vagrant', type: 'winrm' 
    end

    cfg.vm.provider "vmware_desktop" do |v, override|
      override.vm.box = "detectionlab/win10"
      v.vmx["displayname"] = CONFIG[:client][:name]
      v.vmx["gui.fullscreenatpoweron"] = "FALSE"
      v.vmx["gui.viewModeAtPowerOn"] = "windowed"
      v.memory = CONFIG[:client][:memory]
      v.cpus = CONFIG[:client][:cpus]
      v.gui = true
      v.enable_vmrun_ip_lookup = false
    end

    cfg.vm.provider "virtualbox" do |vb, override|
      vb.gui = true
      vb.name = CONFIG[:client][:name]
      vb.default_nic_type = "82545EM"
      vb.customize ["modifyvm", :id, "--memory", CONFIG[:client][:memory]]
      vb.customize ["modifyvm", :id, "--cpus", CONFIG[:client][:cpus]]
      vb.customize ["modifyvm", :id, "--vram", "32"]
      vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["setextradata", "global", "GUI/SuppressMessages", "all" ]

      override.vm.synced_folder './', '/vagrant', type: 'virtualbox'
    end
  end
end
